name: entao_hare
description: "Flutter basic utils"
version: 2.0.7
repository: https://github.com/yangentao/entao_hare
homepage: https://github.com/yangentao/entao_hare

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  println: ^1.0.4
  any_call: ^1.0.1

  entao_dutil: ^2.2.0
  entao_log: ^1.2.8
  entao_range: ^1.0.2
  entao_result: ^1.0.4
  entao_message: ^1.0.0

  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  crypto: ^3.0.6
  package_info_plus: ^9.0.0
  web_socket: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any


